### ISSUE TITLE
Add more resource types

### ISSUE THREAD

**Issue by JeffinSiby** [zowe/cics-for-zowe-client#50]
Discuss with CICS COBOL developers and other users which resources may be most beneficial for their use case in addition to the current 'Programs', 'Local Transactions' and 'Local Files' and implement them.
```[tasklist]
### Tasks
- [ ] zowe/vscode-extension-for-cics#110
- [ ] zowe/cics-for-zowe-client#63
- [ ] zowe/cics-for-zowe-client#43
- [ ] zowe/vscode-extension-for-cics#251
- [ ] https://github.com/zowe/cics-for-zowe-client/issues/49
- [ ] https://github.com/zowe/cics-for-zowe-client/issues/74
- [ ] https://github.com/zowe/cics-for-zowe-client/issues/113
```
